// This file was autogenerated.  Do not edit!
// See callouts-gen.py for more details
#pragma once

#include <string>
#include <tuple>

namespace phosphor
{
namespace logging
{

constexpr auto callouts =
{
    std::make_tuple("/sys/devices/platform/ahb/ahb:apb/1e78a000.i2c/i2c-9/i2c-9/9-004a", "/system/chassis/motherboard"),
    std::make_tuple("/sys/devices/platform/ahb/ahb:apb/1e78a000.i2c/i2c-3/i2c-3/3-0077", "/system/chassis/motherboard"),
    std::make_tuple("/sys/devices/platform/ahb/ahb:apb/1e78a000.i2c/i2c-11/i2c-11/11-0032", "/system/chassis/motherboard/boxelder"),
    std::make_tuple("/sys/devices/hub@00/slave@01:00", "/system/chassis/motherboard/cpu1"),
    std::make_tuple("/sys/devices/platform/ahb/ahb:apb/1e78a000.i2c/i2c-5/i2c-5/5-004c", "/system/chassis/motherboard"),
    std::make_tuple("/sys/devices/platform/ahb/ahb:apb/1e78a000.i2c/i2c-3/i2c-3/3-0060", "/system/chassis/motherboard"),
    std::make_tuple("/sys/devices/platform/ahb/ahb:apb/1e78a000.i2c/i2c-3/i2c-3/3-0052", "/system/chassis/motherboard"),
    std::make_tuple("/sys/devices/platform/fsi-master/slave@00:00", "/system/chassis/motherboard/cpu0"),
    std::make_tuple("/sys/devices/platform/ahb/ahb:apb/1e78a000.i2c/i2c-11/i2c-11/11-0064", "/system/chassis/motherboard"),
    std::make_tuple("/sys/devices/platform/ahb/ahb:apb/1e78a000.i2c/i2c-4/i2c-4/4-004c", "/system/chassis/motherboard"),
    std::make_tuple("/sys/devices/platform/ahb/ahb:apb/1e78a000.i2c/i2c-11/i2c-11/11-0060", "/system/chassis/motherboard"),
    std::make_tuple("/sys/devices/platform/ahb/ahb:apb/1e78a000.i2c/i2c-11/i2c-11/11-0051", "/system/chassis/motherboard/boxelder"),
};

} // namespace logging
} // namespace phosphor
