// This file was autogenerated.  Do not edit!
// See elog-gen.py for more details

#include <string>
#include <vector>
#include <functional>
#include <phosphor-logging/elog-errors.hpp>
#include "elog_meta.hpp"

using namespace phosphor::logging;
using namespace metadata;
using namespace example::xyz::openbmc_project::Example::Elog;
using namespace std::placeholders;

extern const std::map<Metadata, std::function<HandlerType>> meta = {
    {"DEV_ID", std::bind(handler<example::xyz::openbmc_project::Example::Elog::TestErrorTwo::DEV_ID>, _1, _2, _3)},
    {"CALLOUT_DEVICE_PATH_TEST", std::bind(handler<example::xyz::openbmc_project::Example::Device::Callout::CALLOUT_DEVICE_PATH_TEST>, _1, _2, _3)},
    {"CALLOUT_DEVICE_PATH", std::bind(handler<xyz::openbmc_project::Common::Callout::Device::CALLOUT_DEVICE_PATH>, _1, _2, _3)},
};
