## Note that this file is not auto generated, it is what generates the
## elog-lookup.hpp file
// This file was autogenerated.  Do not edit!
// See elog-gen.py for more details
#pragma once

#include <map>
#include <vector>

namespace phosphor
{

namespace logging
{

std::map<std::string,std::vector<std::string>> g_str_vec = {
    % for a in errors:
    <% meta_string = '\",\"'.join(meta[a]) %> \
    {"${errors[a]}",{"${meta_string}"}},
    % endfor
};

} // namespace logging

} // namespace phosphor
