TESTS += $(check_PROGRAMS)

check_PROGRAMS += \
	additional_data_test \
	stream_test

additional_data_test_SOURCES = %reldir%/additional_data_test.cpp
additional_data_test_CPPFLAGS = $(test_cppflags)
additional_data_test_CXXFLAGS = $(test_cxxflags)
additional_data_test_LDADD = $(test_ldadd)
additional_data_test_LDFLAGS = $(test_ldflags)

stream_test_SOURCES = %reldir%/stream_test.cpp
stream_test_CPPFLAGS = $(test_cppflags)
stream_test_CXXFLAGS = $(test_cxxflags)
stream_test_LDADD = $(test_ldadd)
stream_test_LDFLAGS = $(test_ldflags)