TESTS += $(check_PROGRAMS)

check_PROGRAMS += \
	additional_data_test \
	bcd_time_test \
	log_id_test \
	pel_test \
	pel_manager_test \
	private_header_test \
	repository_test \
	section_header_test \
	stream_test \
	user_header_test \
        peltool_test

pel_objects = \
	$(top_builddir)/extensions/openpower-pels/bcd_time.o \
	$(top_builddir)/extensions/openpower-pels/log_id.o \
	$(top_builddir)/extensions/openpower-pels/pel.o \
	$(top_builddir)/extensions/openpower-pels/private_header.o \
	$(top_builddir)/extensions/openpower-pels/user_header.o 

additional_data_test_SOURCES = %reldir%/additional_data_test.cpp 
additional_data_test_CPPFLAGS = $(test_cppflags)
additional_data_test_CXXFLAGS = $(test_cxxflags)
additional_data_test_LDADD = $(test_ldadd)
additional_data_test_LDFLAGS = $(test_ldflags)

stream_test_SOURCES = %reldir%/stream_test.cpp
stream_test_CPPFLAGS = $(test_cppflags)
stream_test_CXXFLAGS = $(test_cxxflags)
stream_test_LDADD = $(test_ldadd)
stream_test_LDFLAGS = $(test_ldflags)

peltool_test_SOURCES = \
         %reldir%/peltool_test.cpp %reldir%/pel_utils.cpp %reldir%/paths.cpp $(top_builddir)/extensions/openpower-pels/tools/peltool_utility.cpp  $(top_builddir)/extensions/openpower-pels/tools/peltool.cpp
peltool_test_CPPFLAGS = $(test_cppflags)
peltool_test_CXXFLAGS = $(test_cxxflags)
peltool_test_LDADD = \
        $(test_ldadd) \
        $(pel_objects)
peltool_test_LDFLAGS = $(test_ldflags)

bcd_time_test_SOURCES = \
	%reldir%/bcd_time_test.cpp
bcd_time_test_CPPFLAGS = $(test_cppflags)
bcd_time_test_CXXFLAGS = $(test_cxxflags)
bcd_time_test_LDADD = \
	$(test_ldadd) \
	$(top_builddir)/extensions/openpower-pels/bcd_time.o
bcd_time_test_LDFLAGS = $(test_ldflags)

section_header_test_SOURCES = \
	%reldir%/section_header_test.cpp
section_header_test_CPPFLAGS = $(test_cppflags)
section_header_test_CXXFLAGS = $(test_cxxflags)
section_header_test_LDADD = $(test_ldadd)
section_header_test_LDFLAGS = $(test_ldflags)

private_header_test_SOURCES = \
	%reldir%/private_header_test.cpp %reldir%/pel_utils.cpp %reldir%/paths.cpp
private_header_test_CPPFLAGS = $(test_cppflags)
private_header_test_CXXFLAGS = $(test_cxxflags)
private_header_test_LDADD = \
	$(test_ldadd) \
	$(pel_objects)
private_header_test_LDFLAGS = $(test_ldflags)

user_header_test_SOURCES = \
	%reldir%/user_header_test.cpp %reldir%/pel_utils.cpp %reldir%/paths.cpp 
user_header_test_CPPFLAGS = $(test_cppflags)
user_header_test_CXXFLAGS = $(test_cxxflags)
user_header_test_LDADD = \
	$(test_ldadd) \
	$(pel_objects) 
user_header_test_LDFLAGS = $(test_ldflags)

log_id_test_SOURCES = \
	%reldir%/log_id_test.cpp %reldir%/paths.cpp
log_id_test_CPPFLAGS = $(test_cppflags)
log_id_test_CXXFLAGS = $(test_cxxflags)
log_id_test_LDADD = \
	$(test_ldadd) \
	$(top_builddir)/extensions/openpower-pels/log_id.o
log_id_test_LDFLAGS = $(test_ldflags)

pel_test_SOURCES = \
	%reldir%/pel_test.cpp %reldir%/paths.cpp %reldir%/pel_utils.cpp
pel_test_CPPFLAGS = $(test_cppflags)
pel_test_CXXFLAGS = $(test_cxxflags)
pel_test_LDADD = \
	$(test_ldadd) \
	$(pel_objects)
pel_test_LDFLAGS = $(test_ldflags)

repository_test_SOURCES = \
	%reldir%/repository_test.cpp %reldir%/paths.cpp %reldir%/pel_utils.cpp
repository_test_CPPFLAGS = $(test_cppflags)
repository_test_CXXFLAGS = $(test_cxxflags)
repository_test_LDADD = \
	$(test_ldadd) \
	$(pel_objects) \
	$(top_builddir)/extensions/openpower-pels/repository.o
repository_test_LDFLAGS = $(test_ldflags)

pel_manager_test_SOURCES = \
	%reldir%/pel_manager_test.cpp %reldir%/paths.cpp %reldir%/pel_utils.cpp
pel_manager_test_CPPFLAGS = $(test_cppflags)
pel_manager_test_CXXFLAGS = $(test_cxxflags)
pel_manager_test_LDADD = \
	$(test_ldadd) \
	$(pel_objects) \
	$(top_builddir)/extensions/openpower-pels/manager.o \
	$(top_builddir)/extensions/openpower-pels/repository.o
pel_manager_test_LDFLAGS = $(test_ldflags)
