## Note that this file is not auto generated, it is what generates the
## elog-metadata-postprocess.cpp file
// This file was autogenerated.  Do not edit!
// See elog-gen.py for more details

#include <string>
#include <vector>
#include <functional>
#include <phosphor-logging/elog-errors.hpp>
#include "elog_meta.hpp"

using namespace phosphor::logging;
using namespace metadata;
using namespace example::xyz::openbmc_project::Example::Elog;
using namespace std::placeholders;

extern const std::map<Metadata, std::function<HandlerType>> meta = {
    % for key, value in metadata_process.iteritems():
<%
        type = value.replace(".", "::")
%>\
    {"${key}", std::bind(handler<${type}>, _1, _2, _3)},
    % endfor
};
