## Note that this file is not auto generated, it is what generates the
## elog-lookup.cpp file
// This file was autogenerated.  Do not edit!
// See elog-gen.py for more details
#include <map>
#include <vector>
#include <log_manager.hpp>

namespace phosphor
{

namespace logging
{

const std::map<std::string,std::vector<std::string>> g_errMetaMap = {
    % for name in errors:
<%
    meta_string = ""
    meta_list = []
    if(name in meta and meta[name]):
        meta_list = meta[name]
        meta_string = '\",\"'.join(meta_list)

    parent = parents[name]
    while parent:
        if (parent in meta and meta[parent]):
            parent_meta_short = '\",\"'.join(meta[parent])
            if (meta_string):
                meta_string = meta_string + "\",\"" + parent_meta_short
            else:
                meta_string = parent_meta_short
        parent = parents[parent]
    if ("example.xyz.openbmc_project" not in name):
        index = name.rfind('.')
        name = name[:index] + ".Error" + name[index:]
%>\
    %if (meta_string):
    {"${name}",{"${meta_string}"}},
    %else:
    {"${name}",{}},
    %endif
    % endfor
};

<%
    # Map legacy syslog-style level names to Entry::Level enumerators.
    levelToEntry = {
        "EMERG": "Emergency",
        "ALERT": "Alert",
        "CRIT": "Critical",
        "ERR": "Error",
        "WARNING": "Warning",
        "NOTICE": "Notice",
        "INFO": "Informational",
        "DEBUG": "Debug",
    }
%>\

const std::map<std::string, Entry::Level> g_errLevelMap = {
    % for a in errors:
<%
    name = a
    if ("example.xyz.openbmc_project" not in name):
        index = name.rfind('.')
        name = name[:index] + ".Error" + name[index:]
%>\
    {"${name}", Entry::Level::${levelToEntry[error_lvl[a]]}},
    % endfor
};

} // namespace logging

} // namespace phosphor
