#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
------------------------------------------------------------
THIS FILE IS AUTO-GENERATED - DO NOT EDIT DIRECTLY

Generated by : generate_lut.py
------------------------------------------------------------
"""

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path


# ==========================================================
# CLI
# ==========================================================
def parse_args():
    parser = argparse.ArgumentParser(description="Generate constexpr LUT")
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    return parser.parse_args()


# ==========================================================
# Validation
# ==========================================================
def is_leaf(node):
    return (
        isinstance(node, dict)
        and "afid" in node
        and "originOfCondition" in node
    )


def validate_leaf(node, path):
    # Validate AFID
    if not isinstance(node["afid"], int):
        raise ValueError(f"afid must be int at {path}")

    if node["afid"] < 0:
        raise ValueError(f"afid must be non-negative at {path}")

    # Validate originOfCondition
    if not isinstance(node["originOfCondition"], str):
        raise ValueError(f"originOfCondition must be string at {path}")

    origins = [o.strip() for o in node["originOfCondition"].split(",")]

    if not origins:
        raise ValueError(
            f"originOfCondition must contain at least one path at {path}"
        )

    for origin in origins:
        if not origin:
            raise ValueError(f"Empty originOfCondition entry at {path}")


def validate_node(node, path="root"):
    if is_leaf(node):
        validate_leaf(node, path)
        return

    if not isinstance(node, dict):
        raise ValueError(f"Invalid node at {path}")

    for k, v in node.items():

        if "=" not in k:
            raise ValueError(f"Missing keyword prefix at {path}->{k}")

        validate_node(v, f"{path}->{k}")


def validate_structure(lookup):
    for message, message_val in lookup.items():

        if is_leaf(message_val):
            raise ValueError(
                f"Invalid LUT: Missing lookup key level at {message}"
            )

        validate_node(message_val, message)


def validate_json(data):
    if "lookup" not in data:
        raise ValueError("Missing 'lookup' section")

    validate_structure(data["lookup"])


# ==========================================================
# Helpers
# ==========================================================
def escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def split_patterns(key):
    return [p.strip() for p in key.split("|")]


def split_keyword_pattern(key):
    pos = key.find("=")

    if pos == -1:
        raise ValueError(
            f"Invalid LUT key '{key}'. " "Expected KEYWORD=pattern format."
        )

    return (
        key[:pos].strip(),
        key[pos + 1 :].strip(),
    )


# ==========================================================
# Pattern dedup
# ==========================================================
class PatternPool:
    def __init__(self):
        self.pool = {}

    def get(self, patterns):
        key = tuple(sorted(patterns))
        if key not in self.pool:
            self.pool[key] = f"p_{len(self.pool)}"
        return self.pool[key]

    def emit(self, out):
        for patterns, name in sorted(self.pool.items(), key=lambda x: x[1]):
            out.write(f"constexpr std::string_view {name}[] = {{\n")
            for p in patterns:
                out.write(f'    "{escape(p)}",\n')
            out.write("};\n\n")


# ==========================================================
# Code generation
# ==========================================================
def generate(data, out_path, input_file):
    lookup = data["lookup"]
    fallback = int(data.get("fallthrough_afid", 0))

    pool = PatternPool()

    # Collect patterns
    def collect(node):
        if is_leaf(node):
            return
        for k, v in sorted(node.items()):
            _, pattern = split_keyword_pattern(k)
            pool.get(split_patterns(pattern))
            collect(v)

    for _, message_node in sorted(lookup.items()):
        collect(message_node)

    with open(out_path, "w") as out:

        # ===== Header =====
        out.write("// SPDX-License-Identifier: Apache-2.0\n")
        out.write(
            "// ------------------------------------------------------------\n"
        )
        out.write("// THIS FILE IS AUTO-GENERATED - DO NOT EDIT DIRECTLY\n")
        out.write("//\n")
        out.write("// Generated by : generate_lut.py\n")
        out.write(f"// Input file : {input_file}\n")
        out.write(f"// Build time : {datetime.now(UTC)}\n")
        out.write(
            "// ------------------------------------------------------------\n\n"
        )

        out.write("#pragma once\n\n")
        out.write("#include <cstdint>\n")
        out.write("#include <string_view>\n")
        out.write("#include <vector>\n\n")

        out.write(
            "struct AFIDResult { "
            "uint64_t afid; "
            "std::vector<std::string_view> origins; "
            "};\n\n"
        )

        # ===== Match functions =====
        out.write(
            "constexpr bool matchPattern(std::string_view s, std::string_view p){\n"
        )
        out.write('    if(p=="*") return true;\n')
        out.write("    auto i=p.find('*');\n")
        out.write("    if(i==std::string_view::npos) return s==p;\n")
        out.write("    auto pre=p.substr(0,i);\n")
        out.write("    auto suf=p.substr(i+1);\n")
        out.write(
            "    if(!pre.empty() && s.substr(0, pre.size())!=pre) return false;\n"
        )
        out.write(
            "    if(!suf.empty() && s.substr(s.size()-suf.size())!=suf) return false;\n"
        )
        out.write("    return true;\n")
        out.write("}\n\n")

        out.write("template<size_t N>\n")
        out.write(
            "constexpr bool matchAny(std::string_view v,const std::string_view(&a)[N]){\n"
        )
        out.write("    for(auto p:a) if(matchPattern(v,p)) return true;\n")
        out.write("    return false;\n")
        out.write("}\n\n")

        out.write(
            "inline std::string_view getValue(\n"
            "    const std::vector<std::string>& additionalData,\n"
            "    std::string_view key)\n"
            "{\n"
            "    for (const auto& item : additionalData)\n"
            "    {\n"
            "        auto pos = item.find('=');\n"
            "\n"
            "        if (pos == std::string::npos)\n"
            "        {\n"
            "            continue;\n"
            "        }\n"
            "\n"
            "        std::string_view k(item.data(), pos);\n"
            "\n"
            "        if (k == key)\n"
            "        {\n"
            "            return std::string_view(\n"
            "                item.data() + pos + 1,\n"
            "                item.size() - pos - 1);\n"
            "        }\n"
            "    }\n"
            "\n"
            "    return {};\n"
            "}\n\n"
        )

        pool.emit(out)

        # ===== API =====

        out.write("constexpr AFIDResult lookupAFID(\n")
        out.write("    std::string_view message,\n")
        out.write("    const std::vector<std::string>& additionalData)\n")
        out.write("{\n")

        # Emit tree
        def emit(node, indent):
            ind = " " * indent

            if is_leaf(node):
                origins = [
                    o.strip() for o in node["originOfCondition"].split(",")
                ]

                origins_cpp = ", ".join(
                    f'"{escape(origin)}"' for origin in origins
                )

                out.write(
                    f'{ind}return {{ {node["afid"]}, '
                    f"{{ {origins_cpp} }} }};\n"
                )
                return

            for k, v in sorted(node.items()):

                keyword, pattern = split_keyword_pattern(k)

                arr = pool.get(split_patterns(pattern))

                out.write(
                    f"{ind}if(matchAny("
                    f'getValue(additionalData, "{escape(keyword)}"), '
                    f"{arr})){{\n"
                )

                emit(v, indent + 4)

                out.write(f"{ind}}}\n")

        for message, msgv in sorted(lookup.items()):
            out.write(f'    if(message=="{escape(message)}"){{\n')

            emit(msgv, 8)

            out.write("    }\n")

        out.write(f"    return {{ {fallback}, {{}} }};\n")
        out.write("}\n")


# ==========================================================
# MAIN
# ==========================================================
if __name__ == "__main__":
    args = parse_args()

    with open(args.input) as f:
        data = json.load(f)

    validate_json(data)

    out_file = Path(args.output)
    out_file.parent.mkdir(parents=True, exist_ok=True)

    generate(data, out_file, args.input)

    print(f"[AEL] LUT generated: {out_file}")
