#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
------------------------------------------------------------
THIS FILE IS AUTO-GENERATED - DO NOT EDIT DIRECTLY

Generated by : generate_lut.py
------------------------------------------------------------
"""

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path


# ==========================================================
# CLI
# ==========================================================
def parse_args():
    parser = argparse.ArgumentParser(description="Generate constexpr LUT")
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    return parser.parse_args()


# ==========================================================
# Validation
# ==========================================================
def is_leaf(node):
    return isinstance(node, dict) and not any(
        isinstance(v, dict) for v in node.values()
    )


def validate_leaf(node, path):
    # Validate afid presence
    if "afid" not in node:
        raise ValueError(f"Missing 'afid' at {path}")

    # Validate AFID type
    if not isinstance(node["afid"], int):
        raise ValueError(f"afid must be int at {path}")

    if node["afid"] < 0:
        raise ValueError(f"afid must be non-negative at {path}")

    # Validate originOfCondition presence
    if "originOfCondition" not in node:
        raise ValueError(f"Missing 'originOfCondition' at {path}")

    # Validate originOfCondition type
    if not isinstance(node["originOfCondition"], str):
        raise ValueError(f"originOfCondition must be string at {path}")

    origins = [o.strip() for o in node["originOfCondition"].split(",")]

    if not origins:
        raise ValueError(
            f"originOfCondition must contain at least one path at {path}"
        )

    for origin in origins:
        if not origin:
            raise ValueError(f"Empty originOfCondition entry at {path}")

    if len(origins) != len(set(origins)):
        raise ValueError(
            f"Duplicate originOfCondition entries at {path}: {origins}"
        )

    # Validate description presence
    if "description" not in node:
        raise ValueError(f"Missing 'description' at {path}")

    if not isinstance(node["description"], str):
        raise ValueError(f"description must be string at {path}")

    if not node["description"].strip():
        raise ValueError(f"Empty description at {path}")

    # Validate redfishMapping presence
    if "redfishMapping" not in node:
        raise ValueError(f"Missing 'redfishMapping' at {path}")

    if not isinstance(node["redfishMapping"], str):
        raise ValueError(f"redfishMapping must be string at {path}")

    redfishMappings = [r.strip() for r in node["redfishMapping"].split(",")]

    if not redfishMappings:
        raise ValueError(
            f"redfishMapping must contain at least one path at {path}"
        )

    for mapping in redfishMappings:
        if not mapping:
            raise ValueError(f"Empty redfishMapping entry at {path}")

    if len(redfishMappings) != len(set(redfishMappings)):
        raise ValueError(
            f"Duplicate redfishMapping entries at {path}: {redfishMappings}"
        )


def match_pattern(value, pattern):
    if pattern == "*":
        return True

    idx = pattern.find("*")

    if idx == -1:
        return value == pattern

    prefix = pattern[:idx]
    suffix = pattern[idx + 1 :]

    if len(value) < len(prefix) + len(suffix):
        return False

    return value.startswith(prefix) and value.endswith(suffix)


def patterns_overlap(a, b):

    if a == b:
        return True

    if "*" not in a and "*" not in b:
        return False

    if "*" in a and match_pattern(b, a):
        return True

    if "*" in b and match_pattern(a, b):
        return True

    return False


def check_overlap(patterns, path):

    expanded = []

    for p in patterns:
        expanded.extend(split_patterns(p))

    for i in range(len(expanded)):
        for j in range(i + 1, len(expanded)):

            a = expanded[i]
            b = expanded[j]

            if patterns_overlap(a, b):
                raise ValueError(
                    f"Overlapping patterns: '{a}' and '{b}' at {path}"
                )


def validate_pattern(pattern, path):
    count = pattern.count("*")

    if count > 1:
        raise ValueError(
            f"Pattern '{pattern}' at {path} contains {count} wildcards. "
            f"Only one '*' per pattern token is supported."
        )


def validate_node(node, path="root"):
    if is_leaf(node):
        validate_leaf(node, path)
        return

    if not isinstance(node, dict):
        raise ValueError(f"Invalid node at {path}")

    _, raw_patterns = zip(*[split_keyword_pattern(k) for k in node.keys()])

    check_overlap(list(raw_patterns), path)

    for k, v in node.items():

        if "=" not in k:
            raise ValueError(f"Missing keyword prefix at {path}->{k}")

        _, raw_pattern = split_keyword_pattern(k)

        for token in split_patterns(raw_pattern):
            if not token:
                raise ValueError(f"Empty pattern token in key '{k}' at {path}")
            validate_pattern(token, f"{path}->{k}")

        validate_node(v, f"{path}->{k}")


def validate_structure(lookup):
    if not lookup:
        raise ValueError(
            "Invalid LUT: lookup must contain at least one message entry"
        )

    if not isinstance(lookup, dict):
        raise ValueError("Invalid LUT: lookup must be a dictionary")

    for message, message_val in lookup.items():

        if is_leaf(message_val):
            raise ValueError(
                f"Invalid LUT: Missing lookup key level at {message}"
            )

        validate_node(message_val, message)


def validate_json(data):
    if "lookup" not in data:
        raise ValueError("Missing 'lookup' section")

    validate_structure(data["lookup"])

    if "fallthrough_afid" not in data:
        raise ValueError("Missing 'fallthrough_afid'")

    if not isinstance(data["fallthrough_afid"], int):
        raise ValueError("'fallthrough_afid' must be integer")

    if "rackUnitPosition" not in data:
        raise ValueError("Missing 'rackUnitPosition'")

    if not isinstance(data["rackUnitPosition"], str):
        raise ValueError("'rackUnitPosition' must be string")

    if not data["rackUnitPosition"].strip():
        raise ValueError("'rackUnitPosition' must not be empty")

    if "schema" not in data:
        raise ValueError("Missing 'schema'")

    if not isinstance(data["schema"], str):
        raise ValueError("'schema' must be string")

    if not data["schema"].strip():
        raise ValueError("'schema' must not be empty")

    if "version" not in data:
        raise ValueError("Missing 'version'")

    if not isinstance(data["version"], str):
        raise ValueError("'version' must be string")

    if not data["version"].strip():
        raise ValueError("'version' must not be empty")


# ==========================================================
# Helpers
# ==========================================================
def escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def split_patterns(key):
    return [p.strip() for p in key.split("|")]


def split_keyword_pattern(key):
    pos = key.find("=")

    if pos == -1:
        raise ValueError(
            f"Invalid LUT key '{key}'. " "Expected KEYWORD=pattern format."
        )

    return (
        key[:pos].strip(),
        key[pos + 1 :].strip(),
    )


# ==========================================================
# Pattern dedup
# ==========================================================
class PatternPool:
    def __init__(self):
        self.pool = {}

    def get(self, patterns):
        key = tuple(sorted(patterns))
        if key not in self.pool:
            self.pool[key] = f"p_{len(self.pool)}"
        return self.pool[key]

    def emit(self, out):
        for patterns, name in sorted(self.pool.items(), key=lambda x: x[1]):
            out.write(f"constexpr std::string_view {name}[] = {{\n")
            for p in patterns:
                out.write(f'    "{escape(p)}",\n')
            out.write("};\n\n")


# ==========================================================
# Code generation
# ==========================================================
def generate(data, out_path, input_file):
    lookup = data["lookup"]
    version = data["version"]
    fallback = int(data.get("fallthrough_afid", 0))
    rack_unit_position = data.get("rackUnitPosition", "")
    schema = data["schema"]

    pool = PatternPool()

    # Collect patterns
    def collect(node):
        if is_leaf(node):
            return
        for k, v in sorted(node.items()):
            _, pattern = split_keyword_pattern(k)
            pool.get(split_patterns(pattern))
            collect(v)

    for _, message_node in sorted(lookup.items()):
        collect(message_node)

    with open(out_path, "w") as out:

        # ===== Header =====
        out.write("// SPDX-License-Identifier: Apache-2.0\n")
        out.write(
            "// ------------------------------------------------------------\n"
        )
        out.write("// THIS FILE IS AUTO-GENERATED - DO NOT EDIT DIRECTLY\n")
        out.write("//\n")
        out.write("// Generated by : generate_lut.py\n")
        out.write(f"// Input file : {Path(input_file).name}\n")
        out.write(f"// Build time : {datetime.now(UTC)}\n")
        out.write(
            "// ------------------------------------------------------------\n\n"
        )

        out.write("#pragma once\n\n")
        out.write("#include <map>\n")
        out.write("#include <vector>\n")
        out.write("#include <string>\n")
        out.write("#include <cstdint>\n")
        out.write("#include <string_view>\n")
        out.write("#include <phosphor-logging/lg2.hpp>\n\n")

        # ===== Top-level constants =====
        out.write(
            f"constexpr std::string_view kVersion = "
            f'"{escape(version)}";\n\n'
        )
        out.write(
            f"constexpr std::string_view kRackUnitPosition = "
            f'"{escape(rack_unit_position)}";\n\n'
        )
        out.write(
            f"constexpr std::string_view kSchema = " f'"{escape(schema)}";\n\n'
        )
        out.write(f"constexpr uint64_t kFallthroughAFID = {fallback};\n\n")

        # ===== Static data struct and getter =====
        out.write(
            "struct AFIDStaticData {\n"
            "    std::string_view version;\n"
            "    uint64_t fallthroughAFID;\n"
            "    std::string_view rackUnitPosition;\n"
            "    std::string_view schema;\n"
            "};\n\n"
        )
        out.write(
            "struct AFIDResult {\n"
            "    uint64_t afid;\n"
            "    std::vector<std::string_view> origins;\n"
            "    std::vector<std::string_view> redfishMappings;\n"
            "    std::string_view description;\n"
            "};\n\n"
        )
        out.write(
            "inline AFIDStaticData getStaticData()\n"
            "{\n"
            "    return {\n"
            "        kVersion,\n"
            "        kFallthroughAFID,\n"
            "        kRackUnitPosition,\n"
            "        kSchema\n"
            "    };\n"
            "}\n\n"
        )

        # ===== Match functions =====
        out.write(
            "constexpr bool matchPattern(std::string_view s, std::string_view p){\n"
        )
        out.write('    if(p=="*") return true;\n')
        out.write("    auto i=p.find('*');\n")
        out.write("    if(i==std::string_view::npos) return s==p;\n")
        out.write("    auto pre=p.substr(0,i);\n")
        out.write("    auto suf=p.substr(i+1);\n")
        out.write("    if(s.size()<pre.size()+suf.size()) return false;\n")
        out.write(
            "    if(!pre.empty() && s.substr(0,pre.size())!=pre) return false;\n"
        )
        out.write(
            "    if(!suf.empty() && s.substr(s.size()-suf.size())!=suf) return false;\n"
        )
        out.write("    return true;\n")
        out.write("}\n\n")

        out.write("template<size_t N>\n")
        out.write(
            "constexpr bool matchAny(std::string_view v,const std::string_view(&a)[N]){\n"
        )
        out.write("    for(auto p:a) if(matchPattern(v,p)) return true;\n")
        out.write("    return false;\n")
        out.write("}\n\n")

        out.write(
            "inline std::string_view getMapValue(\n"
            "    const std::map<std::string, std::string>& additionalData,\n"
            "    std::string_view key)\n"
            "{\n"
            "    auto it = additionalData.find(std::string(key));\n"
            "    if(it == additionalData.end())\n"
            "    {\n"
            "        return {};\n"
            "    }\n"
            "    return it->second;\n"
            "}\n\n"
        )

        pool.emit(out)

        # ===== API =====

        out.write("inline AFIDResult lookupAFID(\n")
        out.write("    std::string_view message,\n")
        out.write(
            "    const std::map<std::string, std::string>& additionalData)\n"
        )
        out.write("{\n")

        out.write(
            "    if(message.empty()){\n"
            '        lg2::warning("[AEL] Empty message string passed to lookupAFID.");\n'
            "        return { 0, {}, {}, {} };\n"
            "    }\n\n"
        )

        # Emit tree
        def emit(node, indent):
            ind = " " * indent

            if is_leaf(node):
                origins = [
                    o.strip() for o in node["originOfCondition"].split(",")
                ]
                origins_cpp = ", ".join(
                    f'"{escape(origin)}"' for origin in origins
                )

                redfishMappings = [
                    r.strip() for r in node["redfishMapping"].split(",")
                ]
                redfishMappings_cpp = ", ".join(
                    f'"{escape(r)}"' for r in redfishMappings
                )

                description_cpp = escape(node["description"])

                out.write(
                    f"{ind}return {{\n"
                    f"{ind}    {node['afid']},\n"
                    f"{ind}    {{ {origins_cpp} }},\n"
                    f"{ind}    {{ {redfishMappings_cpp} }},\n"
                    f'{ind}    "{description_cpp}"\n'
                    f"{ind}}};\n"
                )
                return

            for k, v in sorted(node.items()):
                keyword, pattern = split_keyword_pattern(k)
                arr = pool.get(split_patterns(pattern))
                out.write(
                    f"{ind}if(matchAny("
                    f'getMapValue(additionalData, "{escape(keyword)}"), '
                    f"{arr})){{\n"
                )
                emit(v, indent + 4)
                out.write(f"{ind}}}\n")

        for message, msgv in sorted(lookup.items()):
            out.write(f'    if(message=="{escape(message)}"){{\n')

            emit(msgv, 8)

            # Message matched but no arg matched — return fallback AFID
            out.write(
                f'        lg2::warning("[AEL] Message matched but no arg match. '
                f'Using fallback AFID {fallback}.");\n'
            )
            out.write(f"        return {{ {fallback}, {{}}, {{}}, {{}} }};\n")
            out.write("    }\n")

        # No message matched — return zero AFID with all null data
        out.write("    return { 0, {}, {}, {} };\n")
        out.write("}\n")


# ==========================================================
# MAIN
# ==========================================================
if __name__ == "__main__":
    args = parse_args()

    with open(args.input) as f:
        data = json.load(f)

    validate_json(data)

    out_file = Path(args.output)
    out_file.parent.mkdir(parents=True, exist_ok=True)

    input_file = Path(args.input).name
    generate(data, out_file, input_file)

    print(f"[AEL] LUT generated: {out_file}")
